language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules

before_script:
  - cp ./src/config/config.js.dist  ./src/config/config.js

script:
  - yarn test
  - yarn eslint
  - yarn build
